services:
  postgres:
    image: postgres:18
    container_name: car_dealership_db
    environment:
      POSTGRES_DB: cardealership
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/car-dealership.json
    volumes:
      - ../keycloak/realms:/opt/keycloak/data/import:ro
    command:
      - start-dev
      - --http-port=8081
      - --import-realm
    ports:
     - "8081:8081"