spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cardealership
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false