version: '3.8'

services:

  postgres-storage:
    image: postgres:18
    container_name: storage_db
    environment:
      POSTGRES_DB: storage_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5433:5432"

  postgres-order:
    image: postgres:18
    container_name: order_db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5434:5432"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 8081
      KC_HTTP_ENABLED: true

    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import:ro
    command:
      - start-dev
      - --http-port=8081
      - --import-realm
    ports:
      - "8081:8081"
    depends_on:
      - postgres-storage
      - postgres-order

  storage-service:
    build: ../storage-service
    container_name: storage_service
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - postgres-storage
      - rabbitmq

  order-service:
    build: ../order-service
    container_name: order_service
    ports:
      - "8082:8082"
    depends_on:
      - postgres-order
      - rabbitmq
      - storage-service