server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/order_db
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/car-dealership