server:
  port: 8080

grpc:
  port: 9090

spring:
  application:
    name: storage-service

  datasource:
    url: jdbc:postgresql://postgres-storage:5432/storage_db
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

    drop-first: false

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/car-dealership

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

  instance:
    prefer-ip-address: true