server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/storage_db
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/car-dealership